### ISSUE TITLE
Notification support

### ISSUE THREAD

**Issue by dominic-03** [DiscordMessenger/dm#66] opened 2024-05-16 21:20 UTC
Apologies if this was already requested/considered/rejected.
It would be cool for DM to have notification support in the system tray. For example minimizing the window would send it to the system tray and then if you receive a direct message or are mentioned, it would show a notification balloon on the app icon.

**Comment by iProgramMC** [comment] 2024-05-17 03:05
This is already planned. Looks like I didn't add it anywhere though, oops.

**Comment by Zero3K** [comment] 2024-06-11 20:43
Please add the ability to control which messages get notifications to pop up (such as all messages or only ones that mention the user and replies to DMs).

**Comment by iProgramMC** [comment] 2024-06-11 20:53
You can control that via the official Discord app for now. It follows all the same rules.

**Comment by Zero3K** [comment] 2024-06-11 21:03
Then Do Not Disturb isn't working as intended. I have my status set to that and I still get Notifications in Discord Messenger but not in Discord's Web App.

**Comment by iProgramMC** [comment] 2024-06-12 05:41
Oh, Do not disturb. You didn't mention that in your original request, so I couldn't tell what you are talking about.

**Comment by Zero3K** [comment] 2024-06-12 12:07
The commit you made regarding the issue doesn't fix it for me.

**Comment by Zero3K** [comment] 2024-06-13 15:38
Does it work for you?

**Comment by iProgramMC** [comment] 2024-06-13 17:09
No. I actually found a bug thanks to your tip, so thanks for that. Commit e65ce1af should fix it though. At this point, notification support is pretty much complete, so I'll close this issue.

**Closed by iProgramMC** 2024-06-13 17:09 UTC
Labels: enhancement
