### ISSUE TITLE
doesnt fetch status

### ISSUE THREAD

**Issue by Sinphy** [DiscordMessenger/dm#19] opened 2024-05-09 19:02 UTC
just defaults to invisible, changing it thru app doesnt do anything
![image](https://github.com/DiscordMessenger/dm/assets/68290539/1dc77763-c9df-42e5-8037-970fba5c665a)

**Comment by iProgramMC** [comment] 2024-05-09 20:53
Duplicate of #12.

**Closed by iProgramMC** 2024-05-09 20:53 UTC
